### ISSUE TITLE
Exception in native call from JS

### ISSUE THREAD

**Issue by Arthuzuga** [phuochau/RecordingSample#2]
![Captura de Tela 2019-03-15 às 18 08 05](https://user-images.githubusercontent.com/22326922/54462098-5b389700-474d-11e9-803d-05c7f3f2141f.png)

After that i press to record, the app response with this error at AudioRecorderManager

**Comment by kolyuchii** [comment]
@Arthuzuga Hi! I'm sure this is too late but anyway))

Perhaps the problem is here https://developer.android.com/studio/releases/emulator#disable-host-audio
